### ISSUE TITLE
Right audio channel distorted

### ISSUE THREAD

**Issue by patrickjboettcher** [rorywalsh/CsoundUnity#18]
Unity only recieves audio correctly on the left channel from Csounds audio buffer. The right channel is distorted. There is no increase in amplitude on the right channel.
If I set Unitys Audio Settings from STEREO to MONO no distortion occurs as I am only listening to the left channel.

I tried the csd-file I'm using with a mono and a stereo output. The ksmps value is set to 32.

I'm using the latest development version of Csound Unity.

**Comment by giovannibedetti** [comment]
could you please attach here a zip with a unity scene that shows the problem?

**Comment by patrickjboettcher** [comment]
Here's the simple scene I use:
[CsoundUnity_right_channel_distorted.zip](https://github.com/rorywalsh/CsoundUnity/files/4671678/CsoundUnity_right_channel_distorted.zip)

**Comment by giovannibedetti** [comment]
Sorry for the late reply.
I tried your scene, I can confirm there's some problem with mono files.
Could you try again the latest dev2 branch to see if this is solved?

But what happens in your csd though is that the reverb instrument stops after 8 seconds, determining a drop in the right channel.
The problem is that Unity considers the AudioSource as stereo by default, try setting a mono audioclip to it, without enabling the Process Clip Audio toggle (that would use audio incoming from the audioclip).

**Comment by giovannibedetti** [comment]
Mono csd is fixed in last dev2 branch commit:
https://github.com/rorywalsh/CsoundUnity/commit/82e36f9bfbbe19b446e349049eb4717eef7fe978
Please test the dev2 branch in a clean project via Unity Package Manager clicking on +, Add package from git URL, and paste this url: https://github.com/rorywalsh/CsoundUnity.git#dev2
Wait for the scripts to update and try again.

**Comment by patrickjboettcher** [comment]
Thank you! It does work fine now. One last question before we close this issue: Can you please explain the new "Write Test Score"/"Send Score" section in this branch? I don't really understand its purpose right now.

**Comment by giovannibedetti** [comment]
It's an utility to allow sending a score message to the Csound instance before performance finishes, while in Play Mode. It can be useful to test a csd during development.
If it's confusing I can think of adding a toggle to hide/show this section.

**Comment by giovannibedetti** [comment]
Added foldable sections!

**Comment by patrickjboettcher** [comment]
Thanks!

**Comment by giovannibedetti** [comment]
@all-contributors add @patrickjboettcher for bug
