### ISSUE TITLE
Possible to use Csound Plugin Opcodes?

### ISSUE THREAD

**Issue by Despair-Bear** [rorywalsh/CsoundUnity#23]
This is more of a question than an issue, but is it possible to import the Csound Plugin Opcodes available [here](https://rorywalsh.github.io/csoundPluginOpcodes/#/) to use with the Csound Unity package or would this require some extensive modification to get working?  I saw on a forum thread that you were considering including this in Csound 7.0 release but would like to use sooner if possible.

Thanks in advance :D

**Comment by giovannibedetti** [comment]
Try placing them inside the folder relative to the OS you're using inside the Csound Package. They _should_ work, since we set the Csound Global Environment to that folder. Notice that the first log when you hit play is the path to that folder.
We can think of a better method of adding external plugins in the future!
Notice that if you update the package you will have to copy the libs there again, since the whole CsoundUnity folder could be overridden.

**Comment by rorywalsh** [comment]
If this doesn't work, try adding the opcode library in the CsOptions using the` --opcode-lib=LIBNAME` option.

**Comment by Despair-Bear** [comment]
This seems to have done the trick.  Thank you!
