### ISSUE TITLE
Click and drag of all assets breaks after game playmode is started

### ISSUE THREAD

**Issue by composingcap** [rorywalsh/CsoundUnity#66]
In Unity 2021.2 click and drag support of any assets ceases to work after csound unity is run. It is resolved with a restart of the editor.

**Comment by giovannibedetti** [comment]
Hi Chris, 
This is caused by the virtual keyboard FLTK plugin. It was present in old installations and it's not removed when reinstalling new versions of Csound.
Be sure you don't have a _virtual.dll_ file under:
`C:\Program Files\Csound6_x64\plugins64`
Can you confirm? I cannot replicate the issue anymore on a PC after deleting the above dll.
See https://github.com/rorywalsh/CsoundUnity/issues/42
Here I wrote that the issue was related to how we were destroying Csound, but I confirm it is caused by the virtual keyboard instead.

**Comment by composingcap** [comment]
Deleting the library alone did not seem to work, but a fresh install of 6.8 did the trick (unity crashed with 6.8.1 for me btw)

**Comment by giovannibedetti** [comment]
Uhm the crash could be related with the fact that the Csound version in CsoundUnity is 6.18.
If installing a newer version (6.18.1) of Csound in the system causes a crash, it means that Csound is still trying to load libraries despite the changes we made to avoid that: 
https://github.com/rorywalsh/CsoundUnity/blob/39d8d3ed32f0f3db492dcb160973166fcdf43649/Runtime/CsoundUnityBridge.cs#L121-L122

**Comment by composingcap** [comment]
I am running the release through unity's package manager so maybe that change is not active there yet?

**Comment by giovannibedetti** [comment]
@rorywalsh what do you think of the [above ^](https://github.com/rorywalsh/CsoundUnity/issues/66#issuecomment-1377506855)? 

@composingcap You can install the latest CsoundUnity via PackageManager clicking on the Update button (if available), otherwise simply repeat the importing process from the Package Manager, it will update the package if already installed:

- press the _+ button_
- click _Add Package from GIT url_
- paste this git link: https://github.com/rorywalsh/CsoundUnity.git
- click Add

**Comment by rorywalsh** [comment]
@giovannibedetti, I'm surprised it's still having an issue, but I have ran into the problem in other contexts when I simply installed over existing installs. I think it might only be an issue for the current release. And certainly shouldn't persist into Csound 7.

**Comment by giovannibedetti** [comment]
Closing since this shouldn't be an issue anymore, will reopen in case
